// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package pgx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    id,
    aggregate_id,
    aggregate_type,
    partition_key,
    event_type,
    payload,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEventParams struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	AggregateType AggregateType
	PartitionKey  pgtype.Text
	EventType     EventType
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.AggregateID,
		arg.AggregateType,
		arg.PartitionKey,
		arg.EventType,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const resolveEventBatch = `-- name: ResolveEventBatch :exec
UPDATE events
SET "status" = 'resolved'
WHERE id = ANY($1)
`

func (q *Queries) ResolveEventBatch(ctx context.Context, eventIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resolveEventBatch, eventIds)
	return err
}

const selectOrderEventBatch = `-- name: SelectOrderEventBatch :many
SELECT
    e.id,
    e.aggregate_id,
    e.aggregate_type,
    e.partition_key,
    e.event_type,
    e.payload,
    e.created_at
FROM events e
WHERE e.aggregate_type = 'order' AND
    e.status = 'pending' AND
    e.partition_key = $1
ORDER BY e.id ASC
LIMIT $2
`

type SelectOrderEventBatchParams struct {
	PairKey   pgtype.Text
	BatchSize int32
}

type SelectOrderEventBatchRow struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	AggregateType AggregateType
	PartitionKey  pgtype.Text
	EventType     EventType
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) SelectOrderEventBatch(ctx context.Context, arg SelectOrderEventBatchParams) ([]SelectOrderEventBatchRow, error) {
	rows, err := q.db.Query(ctx, selectOrderEventBatch, arg.PairKey, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectOrderEventBatchRow
	for rows.Next() {
		var i SelectOrderEventBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.PartitionKey,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryLockPair = `-- name: TryLockPair :one
SELECT pg_try_advisory_xact_lock(hashtext($1))
`

func (q *Queries) TryLockPair(ctx context.Context, pairKey string) (bool, error) {
	row := q.db.QueryRow(ctx, tryLockPair, pairKey)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}
