// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgx

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OrderSide string

const (
	OrderSideBid OrderSide = "bid"
	OrderSideAsk OrderSide = "ask"
)

func (e *OrderSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderSide(s)
	case string:
		*e = OrderSide(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderSide: %T", src)
	}
	return nil
}

type NullOrderSide struct {
	OrderSide OrderSide
	Valid     bool // Valid is true if OrderSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderSide) Scan(value interface{}) error {
	if value == nil {
		ns.OrderSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderSide), nil
}

type PairStatus string

const (
	PairStatusHalted  PairStatus = "halted"
	PairStatusTrading PairStatus = "trading"
)

func (e *PairStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PairStatus(s)
	case string:
		*e = PairStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PairStatus: %T", src)
	}
	return nil
}

type NullPairStatus struct {
	PairStatus PairStatus
	Valid      bool // Valid is true if PairStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPairStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PairStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PairStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPairStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PairStatus), nil
}

type Order struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	PairBase  string
	PairQuote string
	Side      OrderSide
	Price     int64
	Amount    int64
	Remaining int64
	CreatedAt pgtype.Timestamptz
}

type Outbox struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	AggregateType string
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	IsCommited    bool
}
