// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package pgx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO orders (
    id,
    user_id,
    pair_base,
    pair_quote,
    side,
    price,
    qty,
    remaining_qty,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertOrderParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	PairBase     string
	PairQuote    string
	Side         OrderSide
	Price        int64
	Qty          int64
	RemainingQty int64
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder,
		arg.ID,
		arg.UserID,
		arg.PairBase,
		arg.PairQuote,
		arg.Side,
		arg.Price,
		arg.Qty,
		arg.RemainingQty,
		arg.CreatedAt,
	)
	return err
}

const selectPairs = `-- name: SelectPairs :many
SELECT DISTINCT
    pair_base,
    pair_quote
FROM orders
`

type SelectPairsRow struct {
	PairBase  string
	PairQuote string
}

func (q *Queries) SelectPairs(ctx context.Context) ([]SelectPairsRow, error) {
	rows, err := q.db.Query(ctx, selectPairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectPairsRow
	for rows.Next() {
		var i SelectPairsRow
		if err := rows.Scan(&i.PairBase, &i.PairQuote); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
