// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pgx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO
    outbox (
        id,
        aggregate_id,
        aggregate_type,
        event_type,
        payload,
        created_at,
        is_commited
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEventParams struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	AggregateType string
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	IsCommited    bool
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.AggregateID,
		arg.AggregateType,
		arg.EventType,
		arg.Payload,
		arg.CreatedAt,
		arg.IsCommited,
	)
	return err
}

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO
    orders (
        id,
        user_id,
        pair_base,
        pair_quote,
        side,
        price,
        amount,
        remaining,
        created_at
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertOrderParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	PairBase  string
	PairQuote string
	Side      OrderSide
	Price     int64
	Amount    int64
	Remaining int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder,
		arg.ID,
		arg.UserID,
		arg.PairBase,
		arg.PairQuote,
		arg.Side,
		arg.Price,
		arg.Amount,
		arg.Remaining,
		arg.CreatedAt,
	)
	return err
}
