// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgx

import (
	"context"
)

type Querier interface {
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertOrder(ctx context.Context, arg InsertOrderParams) error
}

var _ Querier = (*Queries)(nil)
