name: CI

on:
  push:
    branches: ["**"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  buildunit:
    name: Build & Unit
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.26.4"

      - name: Build
        run: go build ./...

      - name: Run tests with coverage
        run: go test -coverprofile=coverage.out -covermode=atomic ./...

      - name: Generate HTML coverage report
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Show total coverage in logs
        run: go tool cover -func=coverage.out

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.out
            coverage.html
          retention-days: 14

      - name: Prepare Pages artifact
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p public
          mv coverage.html public/index.html

      - name: Upload Pages artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - uses: actions/deploy-pages@v4
        id: deployment

  deploy-pages:
    name: Deploy Pages
    needs: buildunit
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-26.04
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
